FROM ruby:3.1.4-alpine
RUN apk add --update --no-cache \
      build-base \
      curl \
      git \
      libffi-dev \
      yarn \
      wget \
      tzdata \
      mysql-dev \
      gcompat

WORKDIR /app

CMD ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]
